name: Deploy to Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.PAT_FOR_ACTIONS }}
          publish_dir: ./
          external_repository: pizzamx/pizzamx.github.io
          publish_branch: master 
          estination_dir: jpgramma
