name: Deploy To GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          repository-name: pizzamx/pizzamx.github.io
          token: ${{ secrets.PAT_FOR_ACTIONS }}
          branch: master
          folder: jpgramma